name: Bug Report
description: Create a report to help us improve Fluent Scrobbler
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: Add any visual context or error logs here if applicable.
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Windows version (e.g., Windows 11 23H2)
    validations:
      required: false
