blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/snw-mint/fluent-scrobbler/discussions
    about: Ask questions or discuss general topics in GitHub Discussions.
